from snakemake.utils import min_version
#min_version('7.32.4') # this is where I started.
min_version('8.20.5') # this is the latest version I have tested.

##### setup report #####
if not config:
    configfile: "../config/config.yaml"
    configfile: "../config/tool_config.yaml"

##### define the workdir for workflow
#workdir: "../test"

#report: "report/workflow.rst"

localrules:
    all,

##### load rules #####
include: "rules/common.smk"
include: "rules/qc.smk"
include: "rules/minimap2_align.smk"
include: "rules/trim_repair.smk"
include: "rules/snv_calling/clair3.smk"
include: "rules/snv_calling/deepvariant.smk"
include: "rules/snv_calling/pepper_deepvariant_margin.smk"
include: "rules/sv_calling/sniffles.smk"
include: "rules/snv_calling/haplotagging.smk"
include: "rules/snv_calling/deepsomatic.smk"
include: "rules/snv_calling/clairS.smk"
include: "rules/sv_calling/nanomonsv.smk"
include: "rules/sv_calling/savana.smk"
include: "rules/sv_calling/severus.smk"


##### target rules #####
rule all:
    input:
        get_final_output(),